config:
- Application-availability(browser): Application-availability(browser).json
- Application-availability(http): Application-availability(http).json
- Application-performance: Application-performance.json
- Service-availability: Service-availability.json
- Service-performance: Service-performance.json
#- Infra-availability(process): Infra-availability(process).json
#- Infra-availability(host): Infra-availability(host).json
#- Infra-resourceCPU(host): Infra-resourceCPU(host).json
#- Infra-resourceMemory(host): Infra-resourceMemory(host).json
Application-availability(browser):
- name: "{{.Env.SLO_PREFIX}} - Application - availability (browser)" 
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
Application-availability(http):
- name: "{{.Env.SLO_PREFIX}} - Application - availability (http)" 
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
Application-performance:
- name: "{{.Env.SLO_PREFIX}} - Application - performance"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
Service-performance:
- name: "{{.Env.SLO_PREFIX}} - Service - performance"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
#linux - metricId: "/calculated-metrics-service/requestcount_sloperf.id"
#windows - metricId: "/todeploy/calculated-metrics-service/requestcount_sloperf.id"
Service-availability:
- name: "{{.Env.SLO_PREFIX}} - Service - availability"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
Infra-availability(process):
- name: "{{.Env.SLO_PREFIX}} - Infrastructure - availability (process)"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
Infra-availability(host):
- name: "{{.Env.SLO_PREFIX}} - Infrastructure - availability (host)"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "95"
- timeframe: "-1w"
- warning_threshold: "98"
Infra-resourceCPU(host):
- name: "{{.Env.SLO_PREFIX}} - Infrastructure - cpu idle (host)"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "10"
- timeframe: "-1w"
- warning_threshold: "20"
Infra-resourceMemory(host):
- name: "{{.Env.SLO_PREFIX}} - Infrastructure - memory available (host)"
- slo_prefix: "{{.Env.SLO_PREFIX}}"
- mzid: "{{.Env.MZID}}"
- target_threshold: "10"
- timeframe: "-1w"
- warning_threshold: "20"
